default_install_hook_types:
  - pre-commit
  - commit-msg


repos:
- hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-docstring-first
  - id: check-json
  - id: check-toml
  - id: check-yaml
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
- hooks:
  - entry: env PYTHONPATH= pyrefly check
    id: pyrefly-check
    language: system
    name: Pyrefly (type checking)
    pass_filenames: true
  repo: https://github.com/facebook/pyrefly-pre-commit
  rev: 0.48.2

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.3.0
  hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]
      args: []
