dataset:
  name: imdb
  num_class: 2
  sequence_length: 256
  vocab_size: 10000
  data_dir: data/dataset_imdb/
  url: "http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz"
  use_cache: true
  num_workers: auto
  pin_memory: true
  prefetch_factor: 2


model:
  name: lstm
  input_dim: 128
  hidden_dim: 256
  num_layers: 2
  weight_tying: false
  pytorch: true
  bidirectional: false

tokenizer:
  name: bpe


task:
  name: classification
  metrics:
    - accuracy
    - f1_score
    - precision
    - recall

train:
  epochs: 15
  batch_size: 64
  multi_gpu: true
  learning_rate: 1e-3
  grad_clip: 1.0
