sequence_length: 100

name: tatoeba
language: eng_nep
data_dir: datasets/dataset_tatoeba_eng_nep/
url: "https://object.pouta.csc.fi/Tatoeba-Challenge-v2023-09-26/eng-nep.tar"

# name: tatoeba
# language: eng_jpn
# data_dir: datasets/dataset_tatoeba_eng_jpn/
# url: "https://object.pouta.csc.fi/Tatoeba-Challenge-v2023-09-26/eng-jpn.tar"

# name: tatoeba_eng_fra
# language: eng_fra
# data_dir: datasets/dataset_tatoeba_eng_fra/
# url: "https://object.pouta.csc.fi/Tatoeba-Challenge-v2023-09-26/eng-fra.tar"

# name: tatoeba_eng_spa
# language: eng_spa
# data_dir: datasets/dataset_tatoeba_eng_spa/
# url: "https://object.pouta.csc.fi/Tatoeba-Challenge-v2023-09-26/eng-spa.tar"

# name: tatoeba_eng_deu
# language: eng_deu
# data_dir: datasets/dataset_tatoeba_eng_deu/
# url: "https://object.pouta.csc.fi/Tatoeba-Challenge-v2023-09-26/eng-deu.tar"
