datasets:
  name: ptb
  sequence_length: 40
  data_dir: datasets/dataset_penn_treebank/
  train_url: "https://raw.githubusercontent.com/tomsercu/lstm/master/data/ptb.train.txt"
  valid_url: "https://raw.githubusercontent.com/tomsercu/lstm/master/data/ptb.valid.txt"
  test_url: "https://raw.githubusercontent.com/tomsercu/lstm/master/data/ptb.test.txt"

models:
  name: lstm
  input_dim: 300
  hidden_dim: 650
  num_layers: 2
  dropout: 0.5
  bidirectional: false
  weight_tying: true

train:
  epochs: 40
  batch_size: 32
  multi_gpu: true
  optimizer: sgd
  learning_rate: 20.0
  lr_decay: 0.5
  grad_clip: 0.25

tasks:
  name: language_modeling
  metrics:
    - perplexity
