dataset:
  name: imdb
  sequence_length: 256
  data_dir: dataset/dataset_imdb/
  url: "http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz"

  use_cache: true
  num_workers: auto
  pin_memory: true
  prefetch_factor: 2


model:
  name: rnn
  input_dim: 200
  hidden_dim: 200
  num_layers: 1
  dropout: 0.5
  bidirectional: false
  weight_tying: false

task:
  name: sentiment_analysis
  metrics:
    - accuracy
    - f1_score
    - precision
    - recall

train:
  epochs: 40
  batch_size: 32
  multi_gpu: true
  learning_rate: 1e-4
  grad_clip: 0.25
