name: language_modeling
description: "A generative task for predicting the next word."

metrics:
  - perplexity

compatible_models:
  - lstm
  - gru
  - rnn
  - transformer_decoder

compatible_datasets:
  - ptb
