name: sentiment_analysis
description: "A classification task for determining text polarity."

loss: cross_entropy

metrics:
  - accuracy
  - f1_score
  - precision
  - recall

compatible_models:
  - lstm
  - naive_lstm
  - gru
  - rnn
  - seq2seq
  - bi_lstm
  - bi_rnn

compatible_datasets:
  - imdb
  - sst2
