dataset:
  name: ptb
  sequence_length: 150
  vocab_size: 10000
  data_dir: data/dataset_penn_treebank/
  train_url: "https://raw.githubusercontent.com/tomsercu/lstm/master/data/ptb.train.txt"
  valid_url: "https://raw.githubusercontent.com/tomsercu/lstm/master/data/ptb.valid.txt"
  test_url: "https://raw.githubusercontent.com/tomsercu/lstm/master/data/ptb.test.txt"

  use_cache: true
  num_workers: auto
  pin_memory: true
  prefetch_factor: 2

tokenizer:
  name: whitespace

model:
  name: qrnn
  input_dim: 200
  hidden_dim: 1000
  num_layers: 3
  weight_tying: false # requires input and hidden dim both to be same

train:
  epochs: 60
  batch_size: 128
  multi_gpu: true
  optimizer: adam
  learning_rate: 0.002
  lr_decay: 0.25
  grad_clip: 1.0
  weight_decay: 1.2e-6

task:
  name: language_modeling
  metrics:
    - perplexity
